# mapping of local source paths to the location of their content
# TODO: maybe try sourcing content from outside the src directory?
# https://github.com/gatsbyjs/gatsby/issues/5510
/: src/content/basics
graphos: src/content/graphos
technotes: src/content/technotes
