on: 
  workflow_call:
    secrets:
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: netlify/actions/cli@master
        with:
          args: deploy --trigger --prod --message "${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
